### PR TITLE
outlay: fix issue with grid rows inheriting first row height

### PR DESCRIPTION
**Pull request by spywiree-priv**

### CODE REVIEW

**Comment by whereswaldon** [comment]
I am not able to merge this unless you sign-off the changes as per https://gioui.org/doc/contribute#style, but the changeset itself looks good. (feel free to force-push a signed-off commit)

**Comment by spywiree-priv** [comment]
Done

**Comment by spywiree-priv** [comment]
Ping @whereswaldon

**Comment by whereswaldon** [comment]
Thanks, merged!

To git.sr.ht:~whereswaldon/gio-x
   d4cc70e..86446d1  main -> main

**Pull request closed without merging**
