### PR TITLE
share: add Windows support for share-dialog

### PR DESCRIPTION
**Pull request by inkeliz**
Signed-off-by: Inkeliz <inkeliz@inkeliz.com>

### CODE REVIEW

**Comment by whereswaldon** [comment]
You can easily try the feature with a `replace` directive in `go.mod` or a `go work` workspace. I know this PR is ancient, and I'm sorry it's sat for so long. It's hard to find time to review over a thousand lines of platform code.

**Comment by inkeliz** [comment]
I understand. I don't know if that fits gio-x too. The Windows implementation is confusing and relies on the COM API over the Windows RT implementation. Also, it can be optimized. I also noticed one memory leak on iOS, which needs to be fixed.

However... The biggest issue here is the lack of tests. I think if it was "testable" that MAYBE simplify the review because you could review the tests and see if they match the behaviour and take a quick look at the implementation.

I can also push one `demo` for testing, at least for quick demonstrations. Then, I'll try to rebase and see what happens too.

**Comment by whereswaldon** [comment]
> I understand. I don't know if that fits gio-x too. The Windows implementation is confusing and relies on the COM API over the Windows RT implementation. Also, it can be optimized. I also noticed one memory leak on iOS, which needs to be fixed.

Yeah, I'm uncertain of whether this belongs in x also. It's definitely a feature than some apps will want, but I'm not sure how many. I'm also not confident of my ability to maintain such a large volume of code for a feature I don't currently use or understand well. This may be best as a separate repo.

> However... The biggest issue here is the lack of tests. I think if it was "testable" that MAYBE simplify the review because you could review the tests and see if they match the behaviour and take a quick look at the implementation.

Tests would absolutely help, but I have to review the implementation too if I'm going to be responsible for maintaining something. I can't maintain code that I don't understand.

> I can also push one `demo` for testing, at least for quick demonstrations. Then, I'll try to rebase and see what happens too.

Upon reflection, I'd like to request that you host this as a separate module. I don't want to block you any longer than I already have. Demo programs are generally a good idea though. :D

**Comment by gedw99** [comment]
@inkeliz if you want help testing it let me know.  Example would be good with go.mod to whatever version of gio it currently needs

**Comment by gedw99** [comment]
Oh forgot to mention to let me know what repo you use

**Comment by inkeliz** [comment]
I'm moving all packages to https://github.com/gioui-plugins/gio-plugins. Currently, `share` have some bugs, I opened some issues about that too.

Now, I'm going to university and I have less time to work on that. :\

**Comment by gedw99** [comment]
Hey @inkeliz 

Congrats on University.

Will checkout the repo. Thanks for letting me know.

**Pull request closed without merging**
